### ISSUE TITLE
What Scopes are required for Github token?

### ISSUE THREAD

**Issue by LilTrublMakr** [k01ek/netbox-devicetype-importer#13]
What scopes are required for the Github token? I only want to give minimal permissions for hopefully obvious reasons.

**Comment by abhi1693** [comment]
Oy public repo read access is needed

**Comment by k01ek** [comment]
Actually, there are no scopes required for the token

**Comment by phw-lopa** [comment]
I tried it yesterday with no scopes - that didn't work.
I needed to add public_repo scope to make it work

**Comment by LilTrublMakr** [comment]
Same. I tried it with no scopes originally and it would fetch the repo and display the templates, but would not allow the downloads.

**Comment by k01ek** [comment]
hmm, its strange.. I tested token without any permissions and it works fine.
