### ISSUE TITLE
Maximum version bump

### ISSUE THREAD

**Issue by LilTrublMakr** [k01ek/netbox-devicetype-importer#16]
Since version 3.3 came out, I have had to disable this plugin so Netbox can start. Log output shows `django.core.exceptions.ImproperlyConfigured: Plugin netbox_devicetype_importer requires NetBox maximum version 3.2.99.`

Can you please bump the maximum version so that the plugin can be used again?

**Comment by faraujo88** [comment]
I had de same problem...

**Comment by reiters-it** [comment]
same to me. please update

**Comment by k01ek** [comment]
#17
