### ISSUE TITLE
Not show devices

### ISSUE THREAD

**Issue by PeterKnotek** [k01ek/netbox-devicetype-importer#4]
Hi. Genereate token on github  ... but no device find ... 

PLUGINS = ['netbox_devicetype_importer' ]
PLUGINS_CONFIG = {
                 'netbox_devicetype_importer':          {
                 'github_token': '<my token>'
                                                        }

Netbo version is :  netbox (v3.1.9)

thanks

**Comment by k01ek** [comment]
Hi @PeterKnotek! Sometimes GitHub API can't process query, just try to load tree one more time. If you got an error, let me see.
