### ISSUE TITLE
Cannot import device if manufacturer already exists

### ISSUE THREAD

**Issue by danjaf** [k01ek/netbox-devicetype-importer#6]
Hello and thank you for coding this Netbox plugin.

I am getting an error when importing a device from the list when the manufacturer already exists within Netbox.

Example steps to reproduce issue:

- Select device "100E" (Manufacturer = Fortinet)
- Press Import Selected

Error message:

> <class 'django.db.utils.IntegrityError'>
> 
> duplicate key value violates unique constraint "dcim_manufacturer_slug_key"
> DETAIL:  Key (slug)=(fortinet) already exists.
> 
> 
> Python version: 3.8.10
> NetBox version: 3.1.10

YAML for this device:

https://github.com/netbox-community/devicetype-library/blob/master/device-types/Fortinet/FG-101F.yaml

<snip>

manufacturer: Fortinet
model: FortiGate 101F
slug: fg-101f
part_number: FG-101F
u_height: 1
is_full_depth: false

</snip>

The error is accurate, as there an existing slug 'fortinet' with in Netbox, with the manufacturer name of 'FORTINET'.

If I change the manufacturer name in Netbox to match the manufacturer in the YAML 'Fortinet', there is no error.

Is there a way to work around this error if the **slug** matches, but the **manufacturer** name already exists in UPPERCASE?

**Comment by k01ek** [comment]
Hi @danjaf ! Thank you for feedback! I think it is possible, but too complicated. Much more easier is rename existing manufacturers.

**Comment by danjaf** [comment]
Fair enough. Thanks for the response!
